### ISSUE TITLE
A docker compose example that works

### ISSUE THREAD

**Issue by renich** [pypiserver/pypiserver#218]
Guys, I'm in the process of creating a k8s deployment of pypiserver. I just wanted to fix the docker-compose.yml so it's updated to the v3.3 format.

```yaml
---
version: "3.3"

services:
    pypiserver:
        image: pypiserver/pypiserver:latest
        volumes:
            - type: bind
              source: ./data
              target: /data
        command: -P /data/.htaccess -a update,download,list /data/packages
        ports:
            - "80:8080"
volumes:
    data:
```

You just need to create "data" and put a `.htaccess` file there with: `htpasswd -c data/.htaccess <username>`.
