### ISSUE TITLE
Docker restart always

### ISSUE THREAD

**Issue by Beachnad** [pypiserver/pypiserver#233]
Not sure if this is a docker issue or an issue with the package, but it would be very useful if `restart: always ` worked.

```
version: '3.3'

services:
  pypi:
    image: pypiserver/pypiserver:latest
    restart: always
    volumes:
      - type: bind
        source: ./packages
        target: /data/packages
    ports:
      - 80:8080

volumes:
    data:
```

The restart feature is working on other docker containers I am running and I just can not figure out why it will not work here. Again, I do not know enough whether this is docker's fault or the package's fault or even possibly my fault.
