### ISSUE TITLE
[BUG] Upload failed (500): with volume

### ISSUE THREAD

**Issue by Hedgehogues** [pypiserver/pypiserver#309]
I start such configuration of docker-compose
```
  pypiserver:
      restart: $RESTART
      image: pypiserver/pypiserver:latest
      volumes:
          - ./.htpasswd:/data/auth/.htpasswd
          - ./packages:/data/packages
      command: -P /data/auth/.htpasswd -a update,download,list /data/packages
      ports:
          - "8081:8080"
```

I have a problem with volume of packages: ` - ./packages:/data/packages`. If I forgot about packages volume, it's all right. But with this line, I have next line while I upload my test package with next command:

`python setup.py bdist_wheel upload -r test`

I have next log:

```
['loguru==0.4.1', 'fastapi==0.54.1', 'uvicorn==0.11.5', 'starlette==0.13.2', 'vault-client==0.3.2', 'prometheus_client==0.7.1']
running bdist_wheel
running build
running build_py
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/xxx
copying build/lib/xxx/__init__.py -> build/bdist.linux-x86_64/wheel/xxx
running install_egg_info
running egg_info
writing xxx.egg-info/PKG-INFO
writing dependency_links to xxx.egg-info/dependency_links.txt
writing entry points to xxx.egg-info/entry_points.txt
writing requirements to xxx.egg-info/requires.txt
writing top-level names to xxx.egg-info/top_level.txt
reading manifest file 'xxx.egg-info/SOURCES.txt'
writing manifest file 'xxx.egg-info/SOURCES.txt'
Copying xxx.egg-info to build/bdist.linux-x86_64/wheel/xxx-0.1.0-py3.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/xxx-0.1.0.dist-info/WHEEL
creating 'dist/xxx-0.1.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'xxx/__init__.py'
adding 'xxx-0.1.0.dist-info/METADATA'
adding 'xxx-0.1.0.dist-info/WHEEL'
adding 'xxx-0.1.0.dist-info/entry_points.txt'
adding 'xxx-0.1.0.dist-info/top_level.txt'
adding 'xxx-0.1.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
running upload
Submitting dist/xxx-0.1.0-py3-none-any.whl to http://0.0.0.0:8081/
Upload failed (500): Internal Server Error
error: Upload failed (500): Internal Server Error
```

**Notice**
If you want try my example completely, you can do next (before start, you need to add `~/.pypirc` and `~/.pip/pip.conf`):

pip install tamplar  # my util for build python layout
mkdir xxx  # create new prject folder
cd xxx
tamplar init  # create layout
python setup.py bdist_wheel upload -r test # upload my package

After that, you can get next log like that, than I pass above

**pip.conf**
```

[global]
index-url = http://abcd:efgh@0.0.0.0:8081
trusted-host = pypi.python.org
	       0.0.0.0
```

**.pypirc**
```

[distutils]
index-servers=
        test

[test]
repository: http://0.0.0.0:8081/
username: eurvanov
password: Tujh1994

```

How I can to solve my problem
