### ISSUE TITLE
Unable to Upload

### ISSUE THREAD

**Issue by usmcamp0811** [pypiserver/pypiserver#329]
Just spent a couple hours trying to upload packages to my `pypiserver` with zero luck. Am I doing something wrong.. or is there a legit bug? Below are all the things I've looked at and configured. My current best guess is that something isn't happen I am trying to do this over HTTP. 

```yaml
version: '3.3'
services:
    pypiserver:
        image: pypiserver/pypiserver:latest
        container_name: "pypi"
        restart: always
        volumes:
            - ./volumes/pypi/pypi-packages:/data/packages
            - ./volumes/pypi/.htpasswd:/data/.htpasswd
        command: -p 8080 -v -P /data/.htpasswd -a update,download,list -d /data /data/packages
        # command: -v /data/packages
        ports:
            - "8080:8080" 
```

I have tried to upload with Poetry and Twine both return 

```bash
[UploadError]
HTTP Error 405: Method Not Allowed
```

I've search high and low and I've seen others reporting similar issue [here](https://github.com/mosquito/pypi-server/issues/17). 

The stdout from the container is:

```bash
 2020-08-20 18:23:27,293|pypiserver.bottle|INFO|139763131985224|Bottle v0.13-dev server starting up (using AutoServer())...
pypi          | 2020-08-20 18:23:27,293|pypiserver.bottle|INFO|139763131985224|Listening on http://0.0.0.0:8080/
pypi          | 2020-08-20 18:23:27,293|pypiserver.bottle|INFO|139763131985224|Hit Ctrl-C to quit.
pypi          |
pypi          | 2020-08-20 18:25:01,412|pypiserver._app|INFO|139763131985224|<LocalRequest: GET http://ef969ea775d8:8080/manager/html>
pypi          | 2020-08-20 18:25:01,412|pypiserver._app|INFO|139763131985224|200 OK
pypi          | /usr/local/lib/python3.6/site-packages/pypiserver/bottle.py:3640: DeprecationWarning: Flags not at the start of the expression '((?mx)         # ver' (truncated)
pypi          |   patterns = [re.compile(p % pattern_vars) for p in patterns]
pypi          | /usr/local/lib/python3.6/site-packages/pypiserver/bottle.py:3640: DeprecationWarning: Flags not at the start of the expression '\\{\\{((?:((?mx)      ' (truncated)
pypi          |   patterns = [re.compile(p % pattern_vars) for p in patterns]
pypi          | 191.232.243.55 - - [20/Aug/2020 18:25:01] "GET /manager/html HTTP/1.1" 404 753
pypi          | 2020-08-20 18:26:25,975|pypiserver._app|INFO|139763131985224|<LocalRequest: POST http://XXXXXXXX.us-east-2.compute.amazonaws.com:8080/simple/>
pypi          | 2020-08-20 18:26:25,975|pypiserver._app|INFO|139763131985224|200 OK
pypi          | 68.32.162.52 - - [20/Aug/2020 18:26:25] "POST /simple/ HTTP/1.1" 405 785
pypi          | 2020-08-20 18:26:34,310|pypiserver._app|INFO|139763131985224|<LocalRequest: POST http://XXXXXXXX.us-east-2.compute.amazonaws.com:8080/simple/>
pypi          | 2020-08-20 18:26:34,311|pypiserver._app|INFO|139763131985224|200 OK
```

`.pypirc`
```
[distutils]
index-servers =
    pypi

[pypi]
repository = http://XXXXX.us-east-2.compute.amazonaws.com:8080/pypi
username: myuser
password: mypassword
```

`~/.config/pypoetry/config.toml`
```toml
[repositories]
[repositories.my_pypi]
url = "http://XXXXXX.us-east-2.compute.amazonaws.com:8080/simple/"
```

Also I have tried installing it locally via `pip install pypiserver` and that was a no go as well.

And I've pulled the repo and rebuilt the Docker Image..
