### ISSUE TITLE
Pip install packages with the docker image

### ISSUE THREAD

**Issue by ArcLightSlavik** [pypiserver/pypiserver#352]
I have a docker-compose of pypi which runs with the default server:

```
  pypi:
    image: &pypi_version pypi:20.10.1
    build:
      context: services/pypi
      dockerfile: Dockerfile
    environment:
      PORT: "8000"
    ports:
      - "8000:8000"
    volumes:
      - ~/code/monitor/services/pypi:/app
    command: -P . -p 8000 -a . /data/packages
```

I want to user gunicorn server so I changed my `command` to:
```
command: -P . -p 8000 -a . --server gunicorn /data/packages
```
But I get a `ModuleNotFoundError: No module named 'gunicorn'` when running it.

I've tried running pip install similar to the pypiserver Dockerfile. It does return `Successfully installed gunicorn-20.0.4` but the module error persists.

```
FROM pypiserver/pypiserver

RUN apk add --no-cache --virtual .build-deps \
        build-base \
        libffi-dev \
    && mkdir /install \
    && python -m pip install --no-warn-script-location \
                --prefix=/install \ 
                gunicorn

EXPOSE 8000
```
